spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minimalProd
    username: minimal_prod_user
    password: minimal_prod_pass

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  graphql:
    execution:
      thread-executor: bean
    schema:
      printer:
        enabled: true

  logging:
    level:
      org.springframework.graphql: DEBUG

flyway:
  enabled: true
  locations: classpath:db/migration
cloudflare:
  r2:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: password123
    bucket: demos
