spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minimalProd
    username: minimal_prod_user
    password: minimal_prod_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: ac9c8a7b2dc5c9bdc3a7fed6888d3c3f
  expiration-ms: 3600000

flyway:
  enabled: true
  locations: classpath:db/migration