spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://localhost:5432/minimalprod
    username: minimal_prod_user
    password: minimal_prod_pass
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        id:
          identifier_generator: Tsid
    show-sql: true

  graphql:
    execution:
      thread-executor: bean
    schema:
      printer:
        enabled: true

  logging:
    level:
      org.springframework.graphql: DEBUG

flyway:
  enabled: true
  locations: classpath:db/migration
cloudflare:
  r2:
    endpoint: https://bucked.minimalprod.space
    access-key: admin
    secret-key: password123
    bucket: demos

