version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: minimal-prod-db
    environment:
      POSTGRES_DB: minimalProd
      POSTGRES_USER: minimal_prod_user
      POSTGRES_PASSWORD: minimal_prod_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de la Aplicaci√≥n Spring Boot
  app:
    build: .
    container_name: minimal-prod-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Sobrescribimos la URL de la datasource para que apunte al servicio 'db'
      # dentro de la red de Docker, no a localhost.
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/minimalProd

volumes:
  postgres_data:
