version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: minimal-prod-db
    environment:
      POSTGRES_DB: minimalProd
      POSTGRES_USER: minimal_prod_user
      POSTGRES_PASSWORD: minimal_prod_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
