version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: minimal-prod-db
    environment:
      POSTGRES_DB: minimalProd
      POSTGRES_USER: minimal_prod_user
      POSTGRES_PASSWORD: minimal_prod_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de la Aplicaci√≥n Spring Boot
  app:
    build: .

    container_name: minimal-prod-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    depends_on:
      - db
    environment:
      - JWT_SECRET=ac9c8a7b2dc5c9bdc3a7fed6888d3c3f
      - JWT_EXPIRATION_MS=3600000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/minimalProd
      - SPRING_DATASOURCE_USERNAME=minimal_prod_user
      - SPRING_DATASOURCE_PASSWORD=minimal_prod_pass


volumes:
  postgres_data:
